// This file is automatically generated during Flutter Web initialization
// It bootstraps the Flutter engine and application

// The value below is injected by flutter build, do not touch.
var serviceWorkerVersion = null;

async function bootstrap() {
  // Load the Flutter engine
  const script = document.createElement('script');
  script.src = 'flutter.js';
  script.type = 'text/javascript';
  document.body.appendChild(script);

  // Wait for the Flutter.js library to be ready
  await new Promise((resolve) => {
    if (window.flutter) {
      resolve();
    } else {
      window.addEventListener('flutter-first-frame', resolve);
    }
  });

  // Initialize the Flutter engine
  if (window.flutter) {
    try {
      // Initialize the Flutter engine
      await window.flutter.loader.load({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      });
      
      console.log('Flutter engine initialized successfully');
    } catch (e) {
      console.error('Failed to initialize Flutter engine:', e);
    }
  } else {
    console.error('Flutter.js failed to load');
  }
}

// Start the bootstrap process
bootstrap();
